# Complete AQA Subject List with Codes
# Scraped from https://www.aqa.org.uk/qualifications

a_level:
  Accounting: "7127"
  Art_and_Design_Art_Craft: "7201"
  Art_and_Design_Fine_Art: "7202"
  Art_and_Design_Graphic: "7203"
  Art_and_Design_Photography: "7206"
  Art_and_Design_Textile: "7204"
  Art_and_Design_3D: "7205"
  Biology: "7402"
  Business: "7132"
  Chemistry: "7405"
  Computer_Science: "7517"
  Dance: "7237"
  Design_and_Technology: "7552"
  Drama: "7262"
  Economics: "7136"
  English_Language: "7702"
  English_Language_and_Literature: "7707"
  English_Literature_A: "7712"
  English_Literature_B: "7717"
  Environmental_Science: "7447"
  French: "7652"
  Further_Mathematics: "7367"
  Geography: "7037"
  German: "7662"
  History: "7042"
  Law: "7162"
  Mathematics: "7357"
  Media_Studies: "7572"
  Music: "7272"
  Philosophy: "7172"
  Physical_Education: "7582"
  Physics: "7408"
  Politics: "7152"
  Psychology: "7182"
  Religious_Studies: "7062"
  Sociology: "7192"
  Spanish: "7692"

gcse:
  Art_and_Design_Art_Craft: "8201"
  Art_and_Design_Fine_Art: "8202"
  Art_and_Design_Graphic: "8203"
  Art_and_Design_Photography: "8206"
  Art_and_Design_Textile: "8204"
  Art_and_Design_3D: "8205"
  Biology: "8461"
  Business: "8132"
  Chemistry: "8462"
  Chinese_Mandarin: "8673"
  Citizenship_Studies: "8100"
  Combined_Science_Trilogy: "8464"
  Computer_Science: "8525"
  Dance: "8236"
  Design_and_Technology: "8552"
  Drama: "8261"
  Economics: "8136"
  Engineering: "8852"
  English_Language: "8700"
  English_Literature: "8702"
  Food_Preparation_and_Nutrition: "8585"
  French: "8658"
  Geography: "8035"
  German: "8668"
  History: "8145"
  Italian: "8633"
  Mathematics: "8300"
  Media_Studies: "8572"
  Music: "8271"
  Physical_Education: "8582"
  Physics: "8463"
  Polish: "8688"
  Psychology: "8182"
  Religious_Studies: "8062"
  Sociology: "8192"
  Spanish: "8698"
  Statistics: "8382"

# Subject name mapping (for URL construction)
subject_names:
  Accounting: "accounting"
  Art_and_Design_Art_Craft: "art-and-design"
  Art_and_Design_Fine_Art: "art-and-design"
  Art_and_Design_Graphic: "art-and-design"
  Art_and_Design_Photography: "art-and-design"
  Art_and_Design_Textile: "art-and-design"
  Art_and_Design_3D: "art-and-design"
  Biology: "biology"
  Business: "business"
  Chemistry: "chemistry"
  Chinese_Mandarin: "chinese-mandarin"
  Citizenship_Studies: "citizenship-studies"
  Combined_Science_Trilogy: "science"
  Computer_Science: "computer-science"
  Dance: "dance"
  Design_and_Technology: "design-and-technology"
  Drama: "drama"
  Economics: "economics"
  Engineering: "engineering"
  English_Language: "english"
  English_Language_and_Literature: "english"
  English_Literature_A: "english"
  English_Literature_B: "english"
  Environmental_Science: "environmental-science"
  Food_Preparation_and_Nutrition: "food-preparation-and-nutrition"
  French: "french"
  Further_Mathematics: "mathematics"
  Geography: "geography"
  German: "german"
  History: "history"
  Italian: "italian"
  Law: "law"
  Mathematics: "mathematics"
  Media_Studies: "media-studies"
  Music: "music"
  Philosophy: "philosophy"
  Physical_Education: "physical-education"
  Physics: "physics"
  Polish: "polish"
  Politics: "politics"
  Psychology: "psychology"
  Religious_Studies: "religious-studies"
  Sociology: "sociology"
  Spanish: "spanish"
  Statistics: "mathematics"
