# OCR Subject Codes
# Format: {Subject}: {AS Code}-{A-Level Code}-from-{year}

a_level:
  Ancient_History: "H007-H407-from-2017"
  Art_and_Design: "H200-H600-from-2015"
  Biology_A: "H020-H420-from-2015"
  Biology_B: "H022-H422-from-2015"
  Business: "H431-from-2015"  # A-Level only (was H031/H431, now just H431)
  Business_2026: "H036-H436-from-2026"
  Chemistry_A: "H032-H432-from-2015"
  Chemistry_B_Salters: "H033-H433-from-2015"
  Classical_Civilisation: "H008-H408-from-2017"
  Classical_Greek: "H044-H444-from-2015"
  Computer_Science: "H046-H446-from-2015"
  Design_and_Technology: "H004-H404-from-2015"  # Multiple endorsements
  Drama_and_Theatre: "H059-H459-from-2015"
  Economics: "H060-H460-from-2015"
  English_Language: "H070-H470-from-2015"
  English_Language_and_Literature: "H074-H474-from-2015"
  English_Literature: "H072-H472-from-2015"
  Film_Studies: "H010-H410-from-2017"
  Geography: "H081-H481-from-2016"
  Geology: "H014-H414-from-2015"
  History_A: "H105-H505-from-2015"
  Latin: "H043-H443-from-2015"
  Law: "H018-H418-from-2017"
  Mathematics_A: "H230-H240-from-2017"
  Mathematics_A_Further: "H235-H245-from-2017"
  Mathematics_B_MEI: "H630-H640-from-2017"
  Mathematics_B_MEI_Further: "H635-H645-from-2017"
  Media_Studies: "H009-H409-from-2017"
  Music: "H143-H543-from-2015"
  Physical_Education: "H155-H555-from-2016"
  Physics_A: "H156-H556-from-2015"
  Physics_B: "H157-H557-from-2015"
  Psychology: "H167-H567-from-2015"
  Psychology_2026: "H169-H569-from-2026"
  Religious_Studies: "H173-H573-from-2016"
  Sociology: "H180-H580-from-2015"
  Sociology_2026: "H182-H582-from-2026"

gcse:
  Ancient_History: "J051-from-2017"
  Art_and_Design: "J170-J176-from-2016"
  Biology_A: "J247-from-2016"
  Biology_B: "J257-from-2016"
  Business: "J204-from-2017"
  Chemistry_A: "J248-from-2016"
  Chemistry_B: "J258-from-2016"
  Citizenship_Studies: "J270-from-2016"
  Classical_Civilisation: "J199-from-2017"
  Combined_Science_A: "J250-from-2016"
  Combined_Science_B: "J260-from-2016"
  Computer_Science: "J277-from-2020"
  Dance: "J814-from-2016"
  Design_and_Technology: "J310-from-2017"
  Drama: "J316-from-2016"
  Economics: "J205-from-2017"
  English_Language: "J351-from-2015"
  English_Literature: "J352-from-2015"
  Food_Preparation_and_Nutrition: "J309-from-2016"
  French: "J730-from-2016"
  Geography_A: "J382-from-2016"
  Geography_B: "J384-from-2016"
  German: "J731-from-2016"
  History_A: "J410-from-2016"
  History_B: "J411-from-2016"
  Latin: "J282-from-2016"
  Mathematics: "J560-from-2015"
  Media_Studies: "J200-from-2019"
  Music: "J536-from-2016"
  Physical_Education: "J587-from-2016"
  Physics_A: "J249-from-2016"
  Physics_B: "J259-from-2016"
  Religious_Studies: "J625-from-2016"
  Sociology: "J203-from-2017"
  Spanish: "J732-from-2016"

# Subject slug mapping
subject_slugs:
  Ancient_History: "ancient-history"
  Art_and_Design: "art-and-design"
  Biology_A: "biology-a"
  Biology_B: "biology-b-advancing-biology"
  Business: "business"
  Business_2026: "business"
  Chemistry_A: "chemistry-a"
  Chemistry_B_Salters: "chemistry-b-salters"
  Classical_Civilisation: "classical-civilisation"
  Classical_Greek: "classical-greek"
  Computer_Science: "computer-science"
  Design_and_Technology: "design-and-technology"
  Drama_and_Theatre: "drama-and-theatre"
  Economics: "economics"
  English_Language: "english-language"
  English_Language_and_Literature: "english-language-and-literature-emc"
  English_Literature: "english-literature"
  Film_Studies: "film-studies"
  Geography: "geography"
  Geography_A: "geography-a"
  Geography_B: "geography-b"
  Geology: "geology"
  History_A: "history-a"
  History_B: "history-b"
  Latin: "latin"
  Law: "law"
  Mathematics_A: "mathematics-a"
  Mathematics_A_Further: "mathematics-a-further"
  Mathematics_B_MEI: "mathematics-b-mei"
  Mathematics_B_MEI_Further: "mathematics-b-mei-further"
  Mathematics: "mathematics"
  Media_Studies: "media-studies"
  Music: "music"
  Physical_Education: "physical-education"
  Physics_A: "physics-a"
  Physics_B: "physics-b-advancing-physics"
  Psychology: "psychology"
  Psychology_2026: "psychology"
  Religious_Studies: "religious-studies"
  Sociology: "sociology"
  Sociology_2026: "sociology"




